"""add erp tasks

Revision ID: 252496a2318d
Revises: 9c4a8f1d2b3e
Create Date: 2026-04-28 11:46:47.609700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252496a2318d'
down_revision = '9c4a8f1d2b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=40), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('lavoro_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_erp_tasks_assignee_id_users')),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], name=op.f('fk_erp_tasks_cliente_id_clienti')),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], name=op.f('fk_erp_tasks_lavoro_id_lavori')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_tasks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erp_tasks')
    # ### end Alembic commands ###
