"""add erp calendar events

Revision ID: 2638274fa828
Revises: 252496a2318d
Create Date: 2026-04-28 12:01:39.718136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2638274fa828'
down_revision = '252496a2318d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('lavoro_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_erp_calendar_events_assigned_user_id_users')),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], name=op.f('fk_erp_calendar_events_cliente_id_clienti')),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], name=op.f('fk_erp_calendar_events_lavoro_id_lavori')),
    sa.ForeignKeyConstraint(['task_id'], ['erp_tasks.id'], name=op.f('fk_erp_calendar_events_task_id_erp_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_calendar_events'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erp_calendar_events')
    # ### end Alembic commands ###
