"""add erp email logs

Revision ID: 29a2b319a499
Revises: de2b09d62544
Create Date: 2026-04-28 17:40:00.744847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a2b319a499'
down_revision = 'de2b09d62544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('lavoro_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('provider_account', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], name=op.f('fk_erp_email_logs_cliente_id_clienti')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_erp_email_logs_created_by_users')),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], name=op.f('fk_erp_email_logs_lavoro_id_lavori')),
    sa.ForeignKeyConstraint(['task_id'], ['erp_tasks.id'], name=op.f('fk_erp_email_logs_task_id_erp_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_email_logs'))
    )
    with op.batch_alter_table('erp_email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_email_logs_email_address'), ['email_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_email_logs_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_email_logs_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_email_logs_thread_id'))
        batch_op.drop_index(batch_op.f('ix_erp_email_logs_message_id'))
        batch_op.drop_index(batch_op.f('ix_erp_email_logs_email_address'))

    op.drop_table('erp_email_logs')
    # ### end Alembic commands ###
