"""add_preventivo_workflow_fields

Revision ID: 1cf1a8df769e
Revises: da02f8d82e18
Create Date: 2026-05-16 12:41:14.740163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf1a8df769e'
down_revision = 'da02f8d82e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_editorial_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_editorial_publications_cliente_date'))
        batch_op.drop_index(batch_op.f('ix_editorial_publications_cliente_date_platform'))

    with op.batch_alter_table('preventivi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_invio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_followup', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('convertito_in_lavoro_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_preventivi_convertito_in_lavoro_id_lavori'), 'lavori', ['convertito_in_lavoro_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preventivi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_preventivi_convertito_in_lavoro_id_lavori'), type_='foreignkey')
        batch_op.drop_column('convertito_in_lavoro_id')
        batch_op.drop_column('data_followup')
        batch_op.drop_column('data_invio')

    with op.batch_alter_table('erp_editorial_publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_editorial_publications_cliente_date_platform'), ['cliente_id', 'publication_date', 'platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_editorial_publications_cliente_date'), ['cliente_id', 'publication_date'], unique=False)

    # ### end Alembic commands ###
