"""add_fatture_table

Revision ID: 36a67110cca5
Revises: de7822c02c7d
Create Date: 2026-05-20 10:45:34.043500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a67110cca5'
down_revision = 'de7822c02c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_fatture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=True),
    sa.Column('data_emissione', sa.Date(), nullable=False),
    sa.Column('data_scadenza', sa.Date(), nullable=True),
    sa.Column('importo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pagato', sa.Boolean(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], name=op.f('fk_erp_fatture_cliente_id_clienti')),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], name=op.f('fk_erp_fatture_lavoro_id_lavori')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_fatture'))
    )
    with op.batch_alter_table('erp_fatture', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_fatture_cliente_id'), ['cliente_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_fatture', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_fatture_cliente_id'))

    op.drop_table('erp_fatture')
    # ### end Alembic commands ###
