"""Aggiunte tabelle task e files

Revision ID: 7b80d702c52a
Revises: 
Create Date: 2026-01-29 15:01:41.820849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b80d702c52a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lavoro', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_lavoro_lavori'), 'lavori', ['lavoro'], ['id'])
        batch_op.drop_column('task_timestamp')
        batch_op.drop_column('task_name')
        batch_op.drop_column('task_tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_tipo', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('task_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('task_timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_tasks_lavoro_lavori'), type_='foreignkey')
        batch_op.drop_column('note')
        batch_op.drop_column('lavoro')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('tipo')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
