"""add erp financial movements

Revision ID: de2b09d62544
Revises: 2638274fa828
Create Date: 2026-04-28 13:03:23.028569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2b09d62544'
down_revision = '2638274fa828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_financial_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('movement_status', sa.String(length=20), nullable=False),
    sa.Column('expense_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('lavoro_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], name=op.f('fk_erp_financial_movements_cliente_id_clienti')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_erp_financial_movements_created_by_users')),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], name=op.f('fk_erp_financial_movements_lavoro_id_lavori')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_financial_movements'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erp_financial_movements')
    # ### end Alembic commands ###
