"""remove_assignee_fields

Revision ID: de7822c02c7d
Revises: 0007_add_external_quote_title
Create Date: 2026-05-20 09:50:12.494251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7822c02c7d'
down_revision = '0007_add_external_quote_title'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_erp_calendar_events_assigned_user_id_users'), type_='foreignkey')
        batch_op.drop_column('assigned_user_id')

    with op.batch_alter_table('erp_editorial_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_editorial_publications_assigned_user_id'))
        batch_op.drop_constraint(batch_op.f('fk_erp_editorial_publications_assigned_user_id_users'), type_='foreignkey')
        batch_op.drop_column('assigned_user_id')

    with op.batch_alter_table('erp_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_erp_tasks_assignee_id_users'), type_='foreignkey')
        batch_op.drop_column('assignee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_erp_tasks_assignee_id_users'), 'users', ['assignee_id'], ['id'])

    with op.batch_alter_table('erp_editorial_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_erp_editorial_publications_assigned_user_id_users'), 'users', ['assigned_user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_erp_editorial_publications_assigned_user_id'), ['assigned_user_id'], unique=False)

    with op.batch_alter_table('erp_calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_erp_calendar_events_assigned_user_id_users'), 'users', ['assigned_user_id'], ['id'])

    # ### end Alembic commands ###
